// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/v1/inject.proto

package nnetmanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InjectEnvelope is the authenticated container that travels on the wire.
// The payload is only parsed after the MAC has been verified.
type InjectEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version. Receivers drop envelopes with an unknown version
	// without parsing the payload.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Identifies which pre-shared key produced the MAC, so keys can be rotated
	// without a flag day.
	KeyId string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Serialized Advertisement.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// HMAC-SHA256 over a domain-separated concatenation of version, key_id and
	// payload. See internal/inject.Seal for the exact preimage.
	Mac           []byte `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectEnvelope) Reset() {
	*x = InjectEnvelope{}
	mi := &file_api_v1_inject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectEnvelope) ProtoMessage() {}

func (x *InjectEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectEnvelope.ProtoReflect.Descriptor instead.
func (*InjectEnvelope) Descriptor() ([]byte, []int) {
	return file_api_v1_inject_proto_rawDescGZIP(), []int{0}
}

func (x *InjectEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InjectEnvelope) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InjectEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InjectEnvelope) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

// Advertisement is what a controller publishes for one bridge segment.
type Advertisement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// node.id of the publishing controller. Agents keep per-controller state
	// because a single L2 segment spans every host participating in the overlay.
	ControllerId string `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	// VNI of the overlay this segment belongs to.
	Vni uint32 `protobuf:"varint,2,opt,name=vni,proto3" json:"vni,omitempty"`
	// Overlay name, for diagnostics.
	Segment string `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	// Tags configured on the bridge. Agents match these against expect_tags.
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// Publish time (Unix millis), used together with sequence for replay
	// rejection.
	TimestampMs int64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Monotonic per-controller counter, reset when the controller restarts.
	Sequence uint64 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Identifies one complete route set. Reserved for future fragmentation of
	// advertisements that outgrow a single datagram.
	Generation uint64 `protobuf:"varint,7,opt,name=generation,proto3" json:"generation,omitempty"`
	// How long an agent keeps these routes without a refresh.
	LeaseSeconds uint32 `protobuf:"varint,8,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	// Routes to install.
	Routes []*InjectedRoute `protobuf:"bytes,9,rep,name=routes,proto3" json:"routes,omitempty"`
	// Optional default gateway for the segment. Empty means none is offered.
	// Agents install it only when the interface opts in.
	DefaultGateway string `protobuf:"bytes,10,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_api_v1_inject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_api_v1_inject_proto_rawDescGZIP(), []int{1}
}

func (x *Advertisement) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *Advertisement) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

func (x *Advertisement) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *Advertisement) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Advertisement) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Advertisement) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Advertisement) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Advertisement) GetLeaseSeconds() uint32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *Advertisement) GetRoutes() []*InjectedRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Advertisement) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

// InjectedRoute is a single prefix an agent should install.
type InjectedRoute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination in CIDR notation (e.g. "172.16.10.0/24").
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Next-hop address, normally the controller's address on the segment.
	NextHop string `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// Route metric (lower is better).
	Metric        uint32 `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectedRoute) Reset() {
	*x = InjectedRoute{}
	mi := &file_api_v1_inject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectedRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectedRoute) ProtoMessage() {}

func (x *InjectedRoute) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_inject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectedRoute.ProtoReflect.Descriptor instead.
func (*InjectedRoute) Descriptor() ([]byte, []int) {
	return file_api_v1_inject_proto_rawDescGZIP(), []int{2}
}

func (x *InjectedRoute) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *InjectedRoute) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *InjectedRoute) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

var File_api_v1_inject_proto protoreflect.FileDescriptor

const file_api_v1_inject_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/inject.proto\x12\n" +
	"nnetman.v1\"m\n" +
	"\x0eInjectEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\fR\x03mac\"\xd4\x02\n" +
	"\rAdvertisement\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12\x10\n" +
	"\x03vni\x18\x02 \x01(\rR\x03vni\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\a \x01(\x04R\n" +
	"generation\x12#\n" +
	"\rlease_seconds\x18\b \x01(\rR\fleaseSeconds\x121\n" +
	"\x06routes\x18\t \x03(\v2\x19.nnetman.v1.InjectedRouteR\x06routes\x12'\n" +
	"\x0fdefault_gateway\x18\n" +
	" \x01(\tR\x0edefaultGateway\"Z\n" +
	"\rInjectedRoute\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\rR\x06metricB3Z1github.com/nishisan-dev/n-netman/api/v1;nnetmanv1b\x06proto3"

var (
	file_api_v1_inject_proto_rawDescOnce sync.Once
	file_api_v1_inject_proto_rawDescData []byte
)

func file_api_v1_inject_proto_rawDescGZIP() []byte {
	file_api_v1_inject_proto_rawDescOnce.Do(func() {
		file_api_v1_inject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_inject_proto_rawDesc), len(file_api_v1_inject_proto_rawDesc)))
	})
	return file_api_v1_inject_proto_rawDescData
}

var file_api_v1_inject_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_inject_proto_goTypes = []any{
	(*InjectEnvelope)(nil), // 0: nnetman.v1.InjectEnvelope
	(*Advertisement)(nil),  // 1: nnetman.v1.Advertisement
	(*InjectedRoute)(nil),  // 2: nnetman.v1.InjectedRoute
}
var file_api_v1_inject_proto_depIdxs = []int32{
	2, // 0: nnetman.v1.Advertisement.routes:type_name -> nnetman.v1.InjectedRoute
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_inject_proto_init() }
func file_api_v1_inject_proto_init() {
	if File_api_v1_inject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_inject_proto_rawDesc), len(file_api_v1_inject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_inject_proto_goTypes,
		DependencyIndexes: file_api_v1_inject_proto_depIdxs,
		MessageInfos:      file_api_v1_inject_proto_msgTypes,
	}.Build()
	File_api_v1_inject_proto = out.File
	file_api_v1_inject_proto_goTypes = nil
	file_api_v1_inject_proto_depIdxs = nil
}
