// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/v1/nnetman.proto

package nnetmanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StateRequest is sent when initiating state exchange with a peer.
type StateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the requesting node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Current routes exported by this node
	Routes []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// Timestamp of the request (Unix millis)
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_api_v1_nnetman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{0}
}

func (x *StateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *StateRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// StateResponse contains the peer's current state.
type StateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the responding node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Current routes exported by the peer
	Routes []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// Timestamp of the response (Unix millis)
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Whether the peer accepted our routes
	Accepted      bool `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_api_v1_nnetman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{1}
}

func (x *StateResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StateResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *StateResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *StateResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// Route represents a network route announcement.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network prefix in CIDR notation (e.g., "172.16.10.0/24" or "2001:db8::/32")
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Next-hop IP address (typically the overlay IP of the announcing node)
	NextHop string `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	// Route metric/preference (lower is better)
	Metric uint32 `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"`
	// Lease duration in seconds (route expires if not refreshed)
	LeaseSeconds uint32 `protobuf:"varint,4,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	// Optional: tags/communities for policy matching
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// VNI of the overlay this route belongs to (for multi-overlay support)
	Vni           uint32 `protobuf:"varint,6,opt,name=vni,proto3" json:"vni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_v1_nnetman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Route) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *Route) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetLeaseSeconds() uint32 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *Route) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Route) GetVni() uint32 {
	if x != nil {
		return x.Vni
	}
	return 0
}

// RouteAnnouncement sends new or updated routes to a peer.
type RouteAnnouncement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the announcing node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Routes being announced
	Routes []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// Timestamp of the announcement (Unix millis)
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteAnnouncement) Reset() {
	*x = RouteAnnouncement{}
	mi := &file_api_v1_nnetman_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAnnouncement) ProtoMessage() {}

func (x *RouteAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAnnouncement.ProtoReflect.Descriptor instead.
func (*RouteAnnouncement) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{3}
}

func (x *RouteAnnouncement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteAnnouncement) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteAnnouncement) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// RouteWithdrawal notifies a peer that routes are being removed.
type RouteWithdrawal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the withdrawing node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Prefixes being withdrawn
	Prefixes []string `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	// Timestamp of the withdrawal (Unix millis)
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteWithdrawal) Reset() {
	*x = RouteWithdrawal{}
	mi := &file_api_v1_nnetman_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteWithdrawal) ProtoMessage() {}

func (x *RouteWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteWithdrawal.ProtoReflect.Descriptor instead.
func (*RouteWithdrawal) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{4}
}

func (x *RouteWithdrawal) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteWithdrawal) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *RouteWithdrawal) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// RouteAck acknowledges route announcements or withdrawals.
type RouteAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the routes were accepted
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Number of routes processed
	RoutesProcessed uint32 `protobuf:"varint,2,opt,name=routes_processed,json=routesProcessed,proto3" json:"routes_processed,omitempty"`
	// Error message if not accepted
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteAck) Reset() {
	*x = RouteAck{}
	mi := &file_api_v1_nnetman_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAck) ProtoMessage() {}

func (x *RouteAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAck.ProtoReflect.Descriptor instead.
func (*RouteAck) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{5}
}

func (x *RouteAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RouteAck) GetRoutesProcessed() uint32 {
	if x != nil {
		return x.RoutesProcessed
	}
	return 0
}

func (x *RouteAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// KeepaliveRequest is sent periodically to maintain peer liveness.
type KeepaliveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the sending node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Sequence number for detecting packet loss
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Timestamp (Unix millis)
	TimestampMs   int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	mi := &file_api_v1_nnetman_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{6}
}

func (x *KeepaliveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *KeepaliveRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *KeepaliveRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// KeepaliveResponse acknowledges a keepalive request.
type KeepaliveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the responding node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Echo back the sequence number
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Timestamp (Unix millis)
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Peer's current health status
	Health        *PeerHealth `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveResponse) Reset() {
	*x = KeepaliveResponse{}
	mi := &file_api_v1_nnetman_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveResponse) ProtoMessage() {}

func (x *KeepaliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveResponse.ProtoReflect.Descriptor instead.
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{7}
}

func (x *KeepaliveResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *KeepaliveResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *KeepaliveResponse) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *KeepaliveResponse) GetHealth() *PeerHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

// PeerHealth reports the current health status of a peer.
type PeerHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the peer considers itself healthy
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Number of active routes
	RouteCount uint32 `protobuf:"varint,2,opt,name=route_count,json=routeCount,proto3" json:"route_count,omitempty"`
	// Uptime in seconds
	UptimeSeconds uint64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerHealth) Reset() {
	*x = PeerHealth{}
	mi := &file_api_v1_nnetman_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHealth) ProtoMessage() {}

func (x *PeerHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_nnetman_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHealth.ProtoReflect.Descriptor instead.
func (*PeerHealth) Descriptor() ([]byte, []int) {
	return file_api_v1_nnetman_proto_rawDescGZIP(), []int{8}
}

func (x *PeerHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *PeerHealth) GetRouteCount() uint32 {
	if x != nil {
		return x.RouteCount
	}
	return 0
}

func (x *PeerHealth) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_api_v1_nnetman_proto protoreflect.FileDescriptor

const file_api_v1_nnetman_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/nnetman.proto\x12\n" +
	"nnetman.v1\"u\n" +
	"\fStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x06routes\x18\x02 \x03(\v2\x11.nnetman.v1.RouteR\x06routes\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\x92\x01\n" +
	"\rStateResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x06routes\x18\x02 \x03(\v2\x11.nnetman.v1.RouteR\x06routes\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\"\x9d\x01\n" +
	"\x05Route\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\rR\x06metric\x12#\n" +
	"\rlease_seconds\x18\x04 \x01(\rR\fleaseSeconds\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x10\n" +
	"\x03vni\x18\x06 \x01(\rR\x03vni\"z\n" +
	"\x11RouteAnnouncement\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x06routes\x18\x02 \x03(\v2\x11.nnetman.v1.RouteR\x06routes\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"i\n" +
	"\x0fRouteWithdrawal\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bprefixes\x18\x02 \x03(\tR\bprefixes\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"g\n" +
	"\bRouteAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10routes_processed\x18\x02 \x01(\rR\x0froutesProcessed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"j\n" +
	"\x10KeepaliveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"\x9b\x01\n" +
	"\x11KeepaliveResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12.\n" +
	"\x06health\x18\x04 \x01(\v2\x16.nnetman.v1.PeerHealthR\x06health\"n\n" +
	"\n" +
	"PeerHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1f\n" +
	"\vroute_count\x18\x02 \x01(\rR\n" +
	"routeCount\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds2\xa9\x02\n" +
	"\aNNetMan\x12D\n" +
	"\rExchangeState\x12\x18.nnetman.v1.StateRequest\x1a\x19.nnetman.v1.StateResponse\x12E\n" +
	"\x0eAnnounceRoutes\x12\x1d.nnetman.v1.RouteAnnouncement\x1a\x14.nnetman.v1.RouteAck\x12C\n" +
	"\x0eWithdrawRoutes\x12\x1b.nnetman.v1.RouteWithdrawal\x1a\x14.nnetman.v1.RouteAck\x12L\n" +
	"\tKeepalive\x12\x1c.nnetman.v1.KeepaliveRequest\x1a\x1d.nnetman.v1.KeepaliveResponse(\x010\x01B,Z*github.com/nishisan-dev/n-netman/api/v1;nnetmanv1b\x06proto3"

var (
	file_api_v1_nnetman_proto_rawDescOnce sync.Once
	file_api_v1_nnetman_proto_rawDescData []byte
)

func file_api_v1_nnetman_proto_rawDescGZIP() []byte {
	file_api_v1_nnetman_proto_rawDescOnce.Do(func() {
		file_api_v1_nnetman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_nnetman_proto_rawDesc), len(file_api_v1_nnetman_proto_rawDesc)))
	})
	return file_api_v1_nnetman_proto_rawDescData
}

var file_api_v1_nnetman_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_nnetman_proto_goTypes = []any{
	(*StateRequest)(nil),      // 0: nnetman.v1.StateRequest
	(*StateResponse)(nil),     // 1: nnetman.v1.StateResponse
	(*Route)(nil),             // 2: nnetman.v1.Route
	(*RouteAnnouncement)(nil), // 3: nnetman.v1.RouteAnnouncement
	(*RouteWithdrawal)(nil),   // 4: nnetman.v1.RouteWithdrawal
	(*RouteAck)(nil),          // 5: nnetman.v1.RouteAck
	(*KeepaliveRequest)(nil),  // 6: nnetman.v1.KeepaliveRequest
	(*KeepaliveResponse)(nil), // 7: nnetman.v1.KeepaliveResponse
	(*PeerHealth)(nil),        // 8: nnetman.v1.PeerHealth
}
var file_api_v1_nnetman_proto_depIdxs = []int32{
	2, // 0: nnetman.v1.StateRequest.routes:type_name -> nnetman.v1.Route
	2, // 1: nnetman.v1.StateResponse.routes:type_name -> nnetman.v1.Route
	2, // 2: nnetman.v1.RouteAnnouncement.routes:type_name -> nnetman.v1.Route
	8, // 3: nnetman.v1.KeepaliveResponse.health:type_name -> nnetman.v1.PeerHealth
	0, // 4: nnetman.v1.NNetMan.ExchangeState:input_type -> nnetman.v1.StateRequest
	3, // 5: nnetman.v1.NNetMan.AnnounceRoutes:input_type -> nnetman.v1.RouteAnnouncement
	4, // 6: nnetman.v1.NNetMan.WithdrawRoutes:input_type -> nnetman.v1.RouteWithdrawal
	6, // 7: nnetman.v1.NNetMan.Keepalive:input_type -> nnetman.v1.KeepaliveRequest
	1, // 8: nnetman.v1.NNetMan.ExchangeState:output_type -> nnetman.v1.StateResponse
	5, // 9: nnetman.v1.NNetMan.AnnounceRoutes:output_type -> nnetman.v1.RouteAck
	5, // 10: nnetman.v1.NNetMan.WithdrawRoutes:output_type -> nnetman.v1.RouteAck
	7, // 11: nnetman.v1.NNetMan.Keepalive:output_type -> nnetman.v1.KeepaliveResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_nnetman_proto_init() }
func file_api_v1_nnetman_proto_init() {
	if File_api_v1_nnetman_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_nnetman_proto_rawDesc), len(file_api_v1_nnetman_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_nnetman_proto_goTypes,
		DependencyIndexes: file_api_v1_nnetman_proto_depIdxs,
		MessageInfos:      file_api_v1_nnetman_proto_msgTypes,
	}.Build()
	File_api_v1_nnetman_proto = out.File
	file_api_v1_nnetman_proto_goTypes = nil
	file_api_v1_nnetman_proto_depIdxs = nil
}
