// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: api/v1/nnetman.proto

package nnetmanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NNetMan_ExchangeState_FullMethodName  = "/nnetman.v1.NNetMan/ExchangeState"
	NNetMan_AnnounceRoutes_FullMethodName = "/nnetman.v1.NNetMan/AnnounceRoutes"
	NNetMan_WithdrawRoutes_FullMethodName = "/nnetman.v1.NNetMan/WithdrawRoutes"
	NNetMan_Keepalive_FullMethodName      = "/nnetman.v1.NNetMan/Keepalive"
)

// NNetManClient is the client API for NNetMan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NNetMan is the control plane service for n-netman agents.
// It enables route exchange and peer health monitoring between nodes.
type NNetManClient interface {
	// ExchangeState performs initial state synchronization between peers.
	// Called when establishing connection to exchange current routing state.
	ExchangeState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	// AnnounceRoutes sends route announcements to a peer.
	// Used for incremental route updates after initial sync.
	AnnounceRoutes(ctx context.Context, in *RouteAnnouncement, opts ...grpc.CallOption) (*RouteAck, error)
	// WithdrawRoutes notifies a peer that routes are being withdrawn.
	WithdrawRoutes(ctx context.Context, in *RouteWithdrawal, opts ...grpc.CallOption) (*RouteAck, error)
	// Keepalive is a bidirectional stream for health monitoring.
	Keepalive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepaliveRequest, KeepaliveResponse], error)
}

type nNetManClient struct {
	cc grpc.ClientConnInterface
}

func NewNNetManClient(cc grpc.ClientConnInterface) NNetManClient {
	return &nNetManClient{cc}
}

func (c *nNetManClient) ExchangeState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, NNetMan_ExchangeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nNetManClient) AnnounceRoutes(ctx context.Context, in *RouteAnnouncement, opts ...grpc.CallOption) (*RouteAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteAck)
	err := c.cc.Invoke(ctx, NNetMan_AnnounceRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nNetManClient) WithdrawRoutes(ctx context.Context, in *RouteWithdrawal, opts ...grpc.CallOption) (*RouteAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteAck)
	err := c.cc.Invoke(ctx, NNetMan_WithdrawRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nNetManClient) Keepalive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepaliveRequest, KeepaliveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NNetMan_ServiceDesc.Streams[0], NNetMan_Keepalive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeepaliveRequest, KeepaliveResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NNetMan_KeepaliveClient = grpc.BidiStreamingClient[KeepaliveRequest, KeepaliveResponse]

// NNetManServer is the server API for NNetMan service.
// All implementations must embed UnimplementedNNetManServer
// for forward compatibility.
//
// NNetMan is the control plane service for n-netman agents.
// It enables route exchange and peer health monitoring between nodes.
type NNetManServer interface {
	// ExchangeState performs initial state synchronization between peers.
	// Called when establishing connection to exchange current routing state.
	ExchangeState(context.Context, *StateRequest) (*StateResponse, error)
	// AnnounceRoutes sends route announcements to a peer.
	// Used for incremental route updates after initial sync.
	AnnounceRoutes(context.Context, *RouteAnnouncement) (*RouteAck, error)
	// WithdrawRoutes notifies a peer that routes are being withdrawn.
	WithdrawRoutes(context.Context, *RouteWithdrawal) (*RouteAck, error)
	// Keepalive is a bidirectional stream for health monitoring.
	Keepalive(grpc.BidiStreamingServer[KeepaliveRequest, KeepaliveResponse]) error
	mustEmbedUnimplementedNNetManServer()
}

// UnimplementedNNetManServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNNetManServer struct{}

func (UnimplementedNNetManServer) ExchangeState(context.Context, *StateRequest) (*StateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeState not implemented")
}
func (UnimplementedNNetManServer) AnnounceRoutes(context.Context, *RouteAnnouncement) (*RouteAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceRoutes not implemented")
}
func (UnimplementedNNetManServer) WithdrawRoutes(context.Context, *RouteWithdrawal) (*RouteAck, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawRoutes not implemented")
}
func (UnimplementedNNetManServer) Keepalive(grpc.BidiStreamingServer[KeepaliveRequest, KeepaliveResponse]) error {
	return status.Error(codes.Unimplemented, "method Keepalive not implemented")
}
func (UnimplementedNNetManServer) mustEmbedUnimplementedNNetManServer() {}
func (UnimplementedNNetManServer) testEmbeddedByValue()                 {}

// UnsafeNNetManServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NNetManServer will
// result in compilation errors.
type UnsafeNNetManServer interface {
	mustEmbedUnimplementedNNetManServer()
}

func RegisterNNetManServer(s grpc.ServiceRegistrar, srv NNetManServer) {
	// If the following call panics, it indicates UnimplementedNNetManServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NNetMan_ServiceDesc, srv)
}

func _NNetMan_ExchangeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NNetManServer).ExchangeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NNetMan_ExchangeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NNetManServer).ExchangeState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NNetMan_AnnounceRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteAnnouncement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NNetManServer).AnnounceRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NNetMan_AnnounceRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NNetManServer).AnnounceRoutes(ctx, req.(*RouteAnnouncement))
	}
	return interceptor(ctx, in, info, handler)
}

func _NNetMan_WithdrawRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteWithdrawal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NNetManServer).WithdrawRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NNetMan_WithdrawRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NNetManServer).WithdrawRoutes(ctx, req.(*RouteWithdrawal))
	}
	return interceptor(ctx, in, info, handler)
}

func _NNetMan_Keepalive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NNetManServer).Keepalive(&grpc.GenericServerStream[KeepaliveRequest, KeepaliveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NNetMan_KeepaliveServer = grpc.BidiStreamingServer[KeepaliveRequest, KeepaliveResponse]

// NNetMan_ServiceDesc is the grpc.ServiceDesc for NNetMan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NNetMan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nnetman.v1.NNetMan",
	HandlerType: (*NNetManServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeState",
			Handler:    _NNetMan_ExchangeState_Handler,
		},
		{
			MethodName: "AnnounceRoutes",
			Handler:    _NNetMan_AnnounceRoutes_Handler,
		},
		{
			MethodName: "WithdrawRoutes",
			Handler:    _NNetMan_WithdrawRoutes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Keepalive",
			Handler:       _NNetMan_Keepalive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/nnetman.proto",
}
